sudo: false

language: generic

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libc6-i386

before_script:
  - export PATH="$PATH:$PWD"
  - ./install_fasmg
  - wget --no-verbose 'http://wikiti.brandonw.net/index.php?title=84PCE:OS:Include_File&action=raw' --output-document=- | sed -e '/\[\[.*\]\]/d;s/<\/\?pre>//' > ti84pce.inc

script:
  - tests/test

notifications:
  irc:
    channels:
      - "irc.choopa.net#ez80-dev"
    on_success: change
    on_failure: always
    skip_join: true
